services:
  astro:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - node

  node:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "install"]
